### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by vaughany** [gourmet/common-mark#1]
Hi there. I'm installing via composer as shown in the readme, and I get the following:

```
$ php composer.phar require gourmet/common-mark:~1.0
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: cakephp/cakephp[3.0.x-dev, 3.0.7].
    - Can only install one of: cakephp/cakephp[3.0.x-dev, 3.0.7].
    - Can only install one of: cakephp/cakephp[3.0.x-dev, 3.0.7].
    - gourmet/common-mark v1.0.0 requires cakephp/cakephp 3.0.*-dev -> satisfiable by cakephp/cakephp[3.0.x-dev].
    - Installation request for gourmet/common-mark ~1.0 -> satisfiable by gourmet/common-mark[v1.0.0].
    - Installation request for cakephp/cakephp == 3.0.7.0 -> satisfiable by cakephp/cakephp[3.0.7].


Installation failed, reverting ./composer.json to its original content.
```

 I'm quite new to composer so I can't offer any help.  It seems to suggest that a development version of CakePHP is required? For what it's worth the 'require' line in my composer.json for CakePHP is `"cakephp/cakephp": "~3.0"`.

If I can get it installed and working I will do my best to write some documentation for you. Keep up the good work!

**Comment by jadb** [comment]
Thanks for reporting it!

I have now [fixed the issue](https://github.com/gourmet/common-mark/commit/91d99b0a60a73b9cd9eecf1381c02f877585998b) and you should be able to install/use the plugin.

**Comment by vaughany** [comment]
Thank you! I have installed without problems, however (due to my inexperience with CakePHP), I don't know how to get it working.  I am assuming that something like the following needs to go in a controller:

```
public $helpers = ['Gourmet/Commonmark.Commonmark'];
```

...and in my templates:

```
echo $this->Commonmark->makehtml($variable);
```

Any help would be greatly appreciated.

**Comment by jadb** [comment]
I [updated](https://github.com/gourmet/common-mark/commit/ed368a126863deb6581d332a70e4365a0289f819) the README. Let me know if that helps.

**Comment by vaughany** [comment]
Indeed it does help, thank you very much! :+1:
